(function(l){var n=window.AmazonUIPageJS||window.P,p=n._namespace||n.attributeErrors,e=p?p("PageRefreshAsset"):n;e.guardFatal?e.guardFatal(l)(e,window):e.execute(function(){l(e,window)})})(function(l,n,p){l.when("A","page-refresh-state","web-ajax-utility","alt-page-refresh-measurement").register("page-refresh-handler",function(e,k,h,f){var b={},d=e.$,g=p,c=function(a,c){var b=this;b.clientId=a;b.persistentParams={};b.pageRefreshUrlParams="";b.deviceType="";b.doPageRefresh=function(g,f,k,l){b.persistentParams=
d.extend(!0,b.persistentParams,f.Persistent);var n={};d.extend(!0,n,b.persistentParams,f["Non-Persistent"]);f=c;var p=0<=e.contains(f,"?");f=f+(p?"&":"?")+((g?"asin="+g:"")+(b.pageRefreshUrlParams?b.pageRefreshUrlParams:""));for(var y in n)null!=n[y]&&(g=n[y],p=f.slice(-1),f+="?"===p||"&"===p?"":"&",f+=y+"="+g);h.getInstance(a,f,k,l).getContent()};b.addParams=function(a){b.persistentParams=d.extend(!0,b.persistentParams,a);return!0};b.removeParams=function(a){e.each(a,function(a,c){delete b.persistentParams[a]});
return!0};b.createCustomParamsMap=function(a,c){var b={Persistent:{},"Non-Persistent":{}};d.each(a,function(a,c){b.Persistent[a]=c});d.each(c,function(a,c){b["Non-Persistent"][a]=c});return b};b.startMeasurement=function(a,c,b,d){g&&g.start(a,c,b,d)};b.stampImageLoad=function(a){g&&g.stampImageLoad(a)};b.stampFeature=function(a,c){g&&g.stampFeature(a,c)};(function(){var a=k.pageRefreshData;b.pageRefreshUrlParams=a.pageRefreshUrlParams;b.deviceType=a.deviceType})()};return{getHandlerInstance:function(a,
e,h){(null==a||""===a)&&n.ueLogError&&n.ueLogError({message:"Invalid ClientId"},{logLevel:"FATAL",attribution:"PageRefreshAPI",message:"Invalid ClientId passed to getHandlerInstance of dpRefreshHandler"});b[a]||(b[a]=new c(a,e));g||(e=h.config,g=new f(d,e.atf.marker,e.cf.marker),g.init(h.storeID,h.productGroupID));return b[a]}}});l.when("A","page-refresh-handler").register("dp-refresh-handler",function(e,k){function h(f,b,d){this.featureTriggeringRefresh=f.featureName;this.deviceType=
(this.deviceTypeStateData=e.state("detail-page-device-type"))&&this.deviceTypeStateData.deviceType?this.deviceTypeStateData.deviceType:"web";this.pageRefreshUrl=b&&b.pageRefreshUrl?b.pageRefreshUrl:"/gp/twister/ajaxv2";this.clientId="PageRefresh_"+this.deviceType+"_Client";this.DPRefreshHandler=k.getHandlerInstance(this.clientId,this.pageRefreshUrl,d)}h.prototype={doPageRefresh:function(e,b,d,g){try{this.DPRefreshHandler.doPageRefresh(e,b,d,g)}catch(c){n.ueLogError&&n.ueLogError(c,{logLevel:"ERROR",
attribution:this.featureTriggeringRefresh,message:"This error is caused by the doPageRefresh method triggered by - "+this.featureTriggeringRefresh})}},createCustomParamsMap:function(e,b){var d={};try{d=this.DPRefreshHandler.createCustomParamsMap(e,b)}catch(g){n.ueLogError&&n.ueLogError(g,{logLevel:"ERROR",attribution:this.featureTriggeringRefresh,message:"This error is caused by the createCustomParamsMap method triggered by - "+this.featureTriggeringRefresh})}return d},addParams:function(e){return e&&
"object"==typeof e?this.DPRefreshHandler.addParams(e):!1},removeParams:function(e){return e&&"object"==typeof e?this.DPRefreshHandler.removeParams(e):!1},startMeasurement:function(e,b,d,g){try{this.DPRefreshHandler.startMeasurement(e,b,d,g)}catch(c){n.ueLogError&&n.ueLogError(c,{logLevel:"ERROR",attribution:this.featureTriggeringRefresh,message:"This error is caused by the startMeasurement method triggered by - "+this.featureTriggeringRefresh})}},stampImageLoad:function(e){try{this.DPRefreshHandler.stampImageLoad(e)}catch(b){n.ueLogError&&
n.ueLogError(b,{logLevel:"ERROR",attribution:this.featureTriggeringRefresh,message:"This error is caused by the startMeasurement method triggered by - "+this.featureTriggeringRefresh})}},stampFeature:function(e,b){try{this.DPRefreshHandler.stampFeature(e,b)}catch(d){n.ueLogError&&n.ueLogError(d,{logLevel:"ERROR",attribution:this.featureTriggeringRefresh,message:"This error is caused by the startMeasurement method triggered by - "+this.featureTriggeringRefresh})}}};return h});l.when("A","jQuery").register("alt-page-refresh-ajax-scope",
function(e,k){return function(e,f,b){this.scopeName=f;this.url=b;ues("t0",f,n.newTwisterInteractionStartTime);ues("ctb",f,"1");this.signalMarker=function(b){!this.markers[b]||0>=this.markers[b].conditions||0===--this.markers[b].conditions&&"function"==typeof this.markers[b].handler&&this.markers[b].handler()};this.addlongPoleTag=function(b,c){b=b.toLowerCase();this.markers[b]&&0==this.markers[b].conditions&&0==this.markers[b].conditions&&n.ue&&"function"===typeof ue.tag&&ue.tag(c)};this.postData=
function(){var b=this.scopeName;e.ajax({url:this.url,dataType:"text",timeout:4E4,error:function(){},success:function(c,a,d){ues("id",b,c);uex("ld",b)}})};var d=this;this.markers={image:{conditions:1,handler:function(){uet("ne",f);d.signalMarker("af")}},af:{conditions:Twister.atfMarkerCount?Twister.atfMarkerCount:2,handler:function(){uet("af",f);uet("cf",f);d.signalMarker("cf")}},cf:{conditions:Twister.cfMarkerCount?Twister.cfMarkerCount:2,handler:function(){uet("cf",f);d.postData()}}}}});l.when("A",
"jQuery","alt-page-refresh-ajax-scope").register("alt-page-refresh-measurement",function(e,k,h){return function(e,b,d){this.atfMarker=b;this.cfMarker=d;this.scopeCount={};this.ajaxScopes={};this.url="";this.init=function(b,c){this.url="/gp/twister/dynamic-update/ajax-measurement.html/?s="+b+"&pgid="+c+"&deviceType="+Twister.deviceType;Twister.isInstaTwisterEnabled&&(this.url+="&ptd="+Twister.productTypeName)};this.start=function(b,c,a,d){if(n.ue){this.scopeCount[b]||(this.scopeCount[b]=0);var m=b+
(this.scopeCount[b]+1);this.scopeCount[b]++;var k=this.url;c&&(k+="&dimensionType="+c);"undefined"!==typeof a&&(k+="&dimensionCount="+a);"undefined"!==typeof d&&(k+="&dimensionsDisplayType="+d);this.ajaxScopes[b]=new h(e,m,k)}};this.stampImageLoad=function(b){this.ajaxScopes[b]&&(this.ajaxScopes[b].signalMarker("image"),Twister.cfImageLongPollTag&&this.ajaxScopes[b].addlongPoleTag("cf",Twister.cfImageLongPollTag))};this.stampFeature=function(b,c){this.ajaxScopes[c]&&(b===this.atfMarker&&this.ajaxScopes[c].signalMarker("af"),
b===this.cfMarker&&(this.ajaxScopes[c].signalMarker("cf"),Twister.cfHtmlLongPollTag&&this.ajaxScopes[c].addlongPoleTag("cf",Twister.cfHtmlLongPollTag)))};this.stampCustomMetrics=function(b,c){this.ajaxScopes[c]&&uet(b,this.ajaxScopes[c].scopeName)}}});l.when("A","ready").register("page-refresh-state",function(e){var k=e.state("page-refresh-data");e=e.state("detail-page-device-type");var h={};"undefined"!==typeof k&&(h.pageRefreshUrlParams=k.pageRefreshUrlParams);"undefined"!==typeof e&&(h.deviceType=
e.deviceType);return{pageRefreshData:h}});l.when("A","jQuery","dp-js-logger").register("web-ajax-utility",function(e,k,h){function f(b,g,c,a){this.scope=b;this.url=g;this.options=c;this.status=0;this.selected=!1;this.error=this.successData=this.xhr=this._status=p;this.chunks=[];this.doNotAbort=a||!1}var b=new h("WebAjaxUtility");f._objects={};f.prototype._callback=function(){var b=arguments[0],g=Array.prototype.slice.call(arguments,1);"function"===typeof b&&b.apply(self,g)};f.prototype._canAbort=
function(){return!this.doNotAbort&&1===this.status};f.prototype._isAborted=function(){return 3===this.status};f.prototype._getUrl=function(){return this.url};f.prototype._abort=function(){if(1===this.status)try{this.ajaxRequestRefence.abort(),this.status=3}catch(d){b.logFatal(d,{message:" Could not abort ajax request."})}};f.prototype._flushChunkData=function(){var b=this;b.chunks.length&&k.map(b.chunks,function(g){b._callback(b.options.chunk,g)})};f.prototype._request=function(){var b=this;b.ajaxRequestRefence=
e.get(b.url,{params:b.options.params,success:function(g,c,a){b.status=4;b.successData=g;b._status=c;b.xhr=a;b.selected&&b._callback(b.options.success,g,c,a)},error:function(g,c,a){b.status=2;b.xhr=g;b._status=c;b.error=a;b.selected&&b._callback(b.options.error,g,c,a)},abort:function(g){b.status=3;b.xhr=g;b.selected&&b._callback(b.options.abort,g)},chunk:function(g){g&&(b.chunks.push(g),b.selected&&b._callback(b.options.chunk,g))},timeout:b.options.timeout||4E4})};f.prototype.getContent=function(){f._abortRequestsExcept(this);
this.selected=!0;0===this.status?(this.status=1,this._request()):1===this.status?this._flushChunkData():4===this.status&&(this._flushChunkData(),this._callback(this.options.success,this.successData,this._status,this.xhr),e.trigger("a:pageUpdate"))};f._abortRequestsExcept=function(b){k.each(f._objects[b.scope],function(g,c){c._canAbort()&&g!==b._getUrl()&&c._abort()})};f.getInstance=function(b,g,c,a){if(!b||!g||"object"!==typeof c)throw"Incorrect parameter passed.";f._objects[b]=f._objects[b]||{};
var e=f._objects[b][g];e&&e._isAborted()&&(delete f._objects[b][g],e=p);e||(f._objects[b][g]=new f(b,g,c,a,this));return f._objects[b][g]};return f})});